version: '3.8'

services:
  pulse-qa:
    build: .
    ports:
      - "7860:7860"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./text:/app/text
      - ./processed:/app/processed
      - ./chroma_db:/app/chroma_db
